import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ /*Readonly means it is only for the reading */
  children: React.ReactNode;  /*React Node is a type where it has too many things like string , fragemnt etc which accept it in the form of typescript*/
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="relative w-full flex items-center justify-center mt-15">
        <Navbar/>
        </div>
        {children}</body>
    </html>
  );
}
